<p class="h1">Basic</p>

# Python and IPython

Python is a general programming language, created by Guido van Rossum around 1991. Python is a multi-paradigm programming language. It support object-oriented and imperative programming, and features from functional programming. It provides a simple and clear syntax and grammar that make it easy to learn and work with.

Different as C++ or Java, Python is an interpreted language. This means, to execute a Python code we need an interpreter program (a Python interpreter). One of the advantages of interpreted languages is the possibility to interactively write and execute code (REPL read-eval-print-loop) reducing the development time.

IPython (short for Interactive Python) initially created in 2001 by Fernando Perez as an enhanced Python interpreter. IPython is strongly related with the Jupyter project. The IPython notebook is actually a special case of the supported notebooks able to operate over the Jupyter environment. 



In [1]:
?


IPython -- An enhanced Interactive Python

IPython offers a fully compatible replacement for the standard Python
interpreter, with convenient shell features, special commands, command
history mechanism and output results caching.

At your system command line, type 'ipython -h' to see the command line
options available. This document only describes interactive features.

GETTING HELP
------------

Within IPython you have various way to access help:

  ?         -> Introduction and overview of IPython's features (this screen).
  object?   -> Details about 'object'.
  object??  -> More detailed, verbose information about 'object'.
  %quickref -> Quick reference of all IPython specific syntax and magics.
  help      -> Access Python's own help system.

If you are in terminal IPython you can quit this screen by pressing `q`.


MAIN FEATURES
-------------

* Access to the standard Python help with object docstrings and the Python
  manuals. Simply type 'help' (no quotes) to invoke it.

* Ma

In [56]:
%quickref 


IPython -- An enhanced Interactive Python - Quick Reference Card

obj?, obj??      : Get help, or more help for object (also works as
                   ?obj, ??obj).
?foo.*abc*       : List names in 'foo' containing 'abc' in them.
%magic           : Information about IPython's 'magic' % functions.

Magic functions are prefixed by % or %%, and typically take their arguments
without parentheses, quotes or even commas for convenience.  Line magics take a
single % and cell magics are prefixed with two %%.

Example magic function calls:

%alias d ls -F   : 'd' is now an alias for 'ls -F'
alias d ls -F    : Works if 'alias' not a python name
alist = %alias   : Get list of aliases to 'alist'
cd /usr/share    : Obvious. cd -<tab> to choose from visited dirs.
%cd??            : See help AND source for magic %cd
%timeit x=10     : time the 'x=10' statement with high precision.
%%timeit x=2**100
x**100           : time 'x**100' with a setup of 'x=2**100'; setup code is not
                   co

## Basic operations

In [111]:
# arithmetic operations
3 + 5

8

In [116]:
abs(6-9)

3

In [117]:
# Variable assingment
a = 10

In [118]:
a

10

### Conditional

In [119]:
# Simple conditional
if a>5:
    print(a,"greater than five")    

# Boolean variable
result = a<=15

# Conditional 1f/then/else
if result:
    print(a,"less or equal than fifthteen")
else:
    print(a,"greater than fifthteen")

10 greater than five
10 less or equal than fifthteen


In [120]:
result

True

In [121]:
type(result)

bool

### Loops

In [122]:
# for each loop
for x in [2, 5, 6, 8, 7]:
    print(x,x**2)

2 4
5 25
6 36
8 64
7 49


In [123]:
data = range(5)
print(data)

range(0, 5)


In [124]:
for i in data:
    print(i)

0
1
2
3
4


In [125]:
# while loop
x = 5
while x>0:
    print(x)
    x-=1
print("boom")

5
4
3
2
1
boom


### User define functions/procedures

In [126]:
def plus(a,b):
    "Add two given numbers"
    c = a + b
    return c

print("12 + 7 =",plus(12,7))

12 + 7 = 19


In [127]:
help(plus)

Help on function plus in module __main__:

plus(a, b)
    Add two given numbers



In [128]:
def fact(n):
    "Factorial function !n"
    if n<=1:
        return 1
    return n*fact(n-1)

def print_fact(n):
    res = fact(n)
    print("!{} = {}".format(n,res))

print_fact(6)

!6 = 720


## Data types

### Basic data types

In [129]:
# Integer
x = 567
type(x)

int

In [130]:
# Float
x = 12.34
type(x)

float

In [131]:
# String
x = "This is a string"
type(x)

str

In [132]:
x

'This is a string'

### List (Vector)

In [133]:
# List/Vector
x = [2, 5.6, "five", [3.1415, 2.46]]
type(x)

list

In [134]:
# Selecting and element of the list
x[0]

2

In [135]:
x[0] = 45
x

[45, 5.6, 'five', [3.1415, 2.46]]

In [136]:
# List size
len(x)

4

In [137]:
# Add element to the end of the list
x.append(0.47)
x

[45, 5.6, 'five', [3.1415, 2.46], 0.47]

In [138]:
print("{} size:{}".format(x,len(x)))

[45, 5.6, 'five', [3.1415, 2.46], 0.47] size:5


In [139]:
# List slice
x[1:-1]

[5.6, 'five', [3.1415, 2.46]]

In [140]:
x[3:]

[[3.1415, 2.46], 0.47]

### Dictionary

In [141]:
data = {'name':'John','age':37, 1:'one'}

In [142]:
print(data)

{'name': 'John', 'age': 37, 1: 'one'}


In [143]:
data['age']

37

In [144]:
data['age'] += 3
data

{'name': 'John', 'age': 40, 1: 'one'}

In [145]:
del data[1]
data

{'name': 'John', 'age': 40}

In [146]:
data.keys(),data.values,data.items()

(dict_keys(['name', 'age']),
 <function dict.values>,
 dict_items([('name', 'John'), ('age', 40)]))

In [147]:
for v in data.values():
    print(v)

John
40


## File handling

In [148]:
f = open("data/Advertising.csv","r")

In [149]:
print(f.readline())
print(f.readline())

,TV,radio,newspaper,sales

1,230.1,37.8,69.2,22.1



In [150]:
f.seek(0)
data = f.readlines()
f.close()

In [151]:
print(data[0])
print(data[1])

,TV,radio,newspaper,sales

1,230.1,37.8,69.2,22.1



In [152]:
print(data[0].strip().split(','))
print([float(v) for v in data[1].strip().split(',')])

['', 'TV', 'radio', 'newspaper', 'sales']
[1.0, 230.1, 37.8, 69.2, 22.1]


In [153]:
def read_data(filename):
    data = {'columns':[], 'data':[]}
    try:
        f = open(filename,'r')
        rawdata = f.readlines()
        f.close()
        data['columns'] = rawdata[0].strip().split(',')
        print(data)
        for strrow in rawdata[1:]:
            row = [float(v) for v in strrow.strip().split(',')]
            data['data'].append(row)
    except:
        print(f"Error opening/processing file '{filename}'")
    return data

In [154]:
tbl = read_data('data/Advertising.csv')
tbl

{'columns': ['', 'TV', 'radio', 'newspaper', 'sales'], 'data': []}


{'columns': ['', 'TV', 'radio', 'newspaper', 'sales'],
 'data': [[1.0, 230.1, 37.8, 69.2, 22.1],
  [2.0, 44.5, 39.3, 45.1, 10.4],
  [3.0, 17.2, 45.9, 69.3, 9.3],
  [4.0, 151.5, 41.3, 58.5, 18.5],
  [5.0, 180.8, 10.8, 58.4, 12.9],
  [6.0, 8.7, 48.9, 75.0, 7.2],
  [7.0, 57.5, 32.8, 23.5, 11.8],
  [8.0, 120.2, 19.6, 11.6, 13.2],
  [9.0, 8.6, 2.1, 1.0, 4.8],
  [10.0, 199.8, 2.6, 21.2, 10.6],
  [11.0, 66.1, 5.8, 24.2, 8.6],
  [12.0, 214.7, 24.0, 4.0, 17.4],
  [13.0, 23.8, 35.1, 65.9, 9.2],
  [14.0, 97.5, 7.6, 7.2, 9.7],
  [15.0, 204.1, 32.9, 46.0, 19.0],
  [16.0, 195.4, 47.7, 52.9, 22.4],
  [17.0, 67.8, 36.6, 114.0, 12.5],
  [18.0, 281.4, 39.6, 55.8, 24.4],
  [19.0, 69.2, 20.5, 18.3, 11.3],
  [20.0, 147.3, 23.9, 19.1, 14.6],
  [21.0, 218.4, 27.7, 53.4, 18.0],
  [22.0, 237.4, 5.1, 23.5, 12.5],
  [23.0, 13.2, 15.9, 49.6, 5.6],
  [24.0, 228.3, 16.9, 26.2, 15.5],
  [25.0, 62.3, 12.6, 18.3, 9.7],
  [26.0, 262.9, 3.5, 19.5, 12.0],
  [27.0, 142.9, 29.3, 12.6, 15.0],
  [28.0, 240.1, 16.7, 22.9, 15.

In [155]:
!pwd

/Users/toloosha/My Drive/baharehdocs/research/teaching/alberta/2025-alberta-ece447/notebooks/python


In [156]:
f = open('mydata.txt','w')
f.write("This is the first line\n")
f.write("Is this the secon line?")
f.close()

In [157]:
!cat 'mydata.txt'

This is the first line
Is this the secon line?

## Classes and Objects

In [158]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

p1 = Person("John", 36)

print(p1.name)
print(p1.age) 

John
36


In [159]:
class Pair:
    def __init__(self, aa, b):
        self.a = aa
        self.b = b
    
    def sum(self):
        return self.a + self.b

In [160]:
p1 = Pair(2,5)

print(p1.sum())

7


## Extra functionality

Using *modules* we can extend the functionality of Python

In [161]:
# Importing more math functionality
import math

In [162]:
help(math)

Help on module math:

NAME
    math

MODULE REFERENCE
    https://docs.python.org/3.9/library/math
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in 

In [163]:
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [164]:
type(math)

module

In [165]:
res = math.sqrt(144)
res

12.0

In [166]:
help(math.sqrt)

Help on built-in function sqrt in module math:

sqrt(x, /)
    Return the square root of x.



In [ ]:
# pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 5.3 MB 1.7 MB/s eta 0:00:01
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


# Numpy

*Numpy* (short for Numerical Python) is an open source Python library for scientific computing with Python. Provides support for multidimensional array objects and perform faster mathematical operations. 

To use *numpy* we need to import the numpy module:

In [170]:
import numpy as np


## Numpy Array

To create a Numpy array we need pass a list of element values as an argument to the `np.array()` function.
A matrix (2D array) can be created specifying a list of lists as argument for `np.array` constructor.

In [171]:
array1d = np.array([1, 2, 3, 4, 5, 6])
print(array1d)

array2d = np.array([[1, 2, 3], [4, 5, 6]])
print("-" * 10)
print(array2d)

array3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("-" * 10)
print(array3d)

[1 2 3 4 5 6]
----------
[[1 2 3]
 [4 5 6]]
----------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [172]:
array1d.shape

(6,)

In [173]:
array2d.shape

(2, 3)

In [174]:
array3d.shape

(2, 2, 3)

In [175]:
array1d.size, array2d.size, array3d.size

(6, 6, 12)

In [176]:
array1d.ndim, array2d.ndim, array3d.ndim

(1, 2, 3)

In [177]:
array1d.dtype

dtype('int64')

In [178]:
mat = np.array([[1,2],[3.0, 4]])
mat.dtype

dtype('float64')

### Data types

- `int`  : Integer (`int8`, `int16`, `int32`, `int64`)
- `uint` : Unsigned integer (`uint8`, `uint16`, `uint32`, `uint64`)
- `bool` : Boolean (`True`,`False`)
- `float`: Floating-point numbers (`float16`, `float32`, `float64`, `float128`)
- `complex` : Complex-valued floating point (`complex64`, `complex128`, `complex256`)

In [179]:
array = np.array(["One", "Two", "three"])
array.dtype

dtype('<U5')

### Array resizing and reshaping

The `resize`method modifies existing shape and array itself.

In [180]:
array = np.array([1,2,3,4,5,6,7,8,9])
print(array.shape)
print(array)

(9,)
[1 2 3 4 5 6 7 8 9]


In [181]:
array = np.array([1,2,3,4,5,6,7,8,9])
array.resize(11)
print(array.shape)
print(array)

(11,)
[1 2 3 4 5 6 7 8 9 0 0]


In [182]:
array = np.array([1,2,3,4,5,6,7,8,9])
array.resize(2,4)
print(array.shape)
print(array)

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [183]:
array = np.array([1,2,3,4,5,6,7,8,9])
array.resize(3,3)
print(array.shape)
print(array)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [184]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

The `reshape` method modifies existing shape but original array remains unchanged.

In [185]:
array = np.array([1,2,3,4,5,6,7,8])
array2 = array.reshape(2,4)
print("-- array --")
print(array.shape)
print(array)
print("-- array2 --")
print(array2.shape)
print(array2)

-- array --
(8,)
[1 2 3 4 5 6 7 8]
-- array2 --
(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


### Generating arrays

The `arange` function creates an array with evenly spaced values between the specified *start*, *end*, and *increment* values.

In [186]:
array1d = np.arange(5)  # 1 row and 5 columns
print(array1d) 

[0 1 2 3 4]


In [187]:
array1d = np.arange(0, 12, 2)  # 1 row and 6 columns
print(array1d)

[ 0  2  4  6  8 10]


In [188]:
array2d = np.arange(0, 12, 2).reshape(2, 3)  # 2 rows 3 columns
print(array2d)

[[ 0  2  4]
 [ 6  8 10]]


In [ ]:
array3d = np.arange(9).reshape(3, 3)  # 3 rows and columns
print(array3d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


The `linspace` function generates an array with evenly spaced values between specified *start* and *end* values, using a specified number of elements.

In [190]:
array1d = np.linspace(0, 12, 2)
print(array1d) 

[ 0. 12.]


In [191]:
array1d = np.linspace(0, 12, 8)
print(array1d)

[ 0.          1.71428571  3.42857143  5.14285714  6.85714286  8.57142857
 10.28571429 12.        ]


In [ ]:
array2d = np.linspace(0, 12, 12).reshape(4, 3)
print(array2d)

[[ 0.          1.09090909  2.18181818]
 [ 3.27272727  4.36363636  5.45454545]
 [ 6.54545455  7.63636364  8.72727273]
 [ 9.81818182 10.90909091 12.        ]]


The `zeros` function, generates an array with the specified dimensions and filled with *zeros*.

In [193]:
array1d = np.zeros(3)
print(array1d)

[0. 0. 0.]


In [194]:
array2d = np.zeros((2, 4))
print(array2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


The `ones` function, generates an array with the specified dimensions and filled with *ones*.

In [195]:
array1d = np.ones(3)
print(array1d)

[1. 1. 1.]


In [196]:
array2d = np.ones((2, 4))
print(array2d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


The `full` function, generates an array with the specified dimensions and filled with *specified number*.

In [197]:
array1d = np.full((3), 2)
print(array1d)

[2 2 2]


In [198]:
array2d = np.full((2, 4), 3.)
print(array2d)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]]


The `eye` function, returns an array where all elements are equal to zero, except for the k-th diagonal, whose values are equal to one.

In [199]:
array1 = np.eye(3, dtype=int)
print(array1)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [200]:
array2 = np.eye(5, k=2)
print(array2)

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


The `np.random.rand` method, generates an array with random numbers that are *uniformly distributed* [0.0, 1.0).

In [201]:
print(np.random.rand(3, 2))  # Uniformly distributed values.

[[0.00654941 0.96757795]
 [0.84094953 0.29809987]
 [0.93936651 0.14460544]]


The `np.random.randn` method, generates an array with random numbers that are *normally distributed*  (mean 0 and variance 1).

In [202]:
print(np.random.randn(3, 2))  # Normally distributed values.

[[-0.49474836  0.10479673]
 [-0.75097491  0.29458991]
 [-0.47269361 -0.70503724]]


The `np.random.randint` method, generates an array with random numbers that are *uniformly distributed* between 0 and given integer [0.0, number).

In [203]:
print(np.random.randint(2, size=10))

print(np.random.randint(5, size=(2, 4)))

[0 1 0 0 1 1 0 1 1 1]
[[4 2 2 4]
 [4 1 1 3]]


### Identity and Diagonal Array

The `identity` function, generates square array with ones on the main diagonal. 

In [204]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


The `diag` function extract or construct diagonal array.

In [205]:
print(np.diag(np.arange(0, 8, 2)))

[[0 0 0 0]
 [0 2 0 0]
 [0 0 4 0]
 [0 0 0 6]]


### Indexing

In order to access a single or multiple items of an array, we need to pass array of indexes in square brackets.

Indexing in two-dimensional array is represented by a pair of values, where the first value is the index of the row and the second is the index of the column.

In [206]:
array1d = np.array([1, 2, 3, 4, 5, 6])
print(array1d[0])   # Get first value
print(array1d[-1])  # Get last value
print(array1d[3])   # Get 4th value from first
print(array1d[-5])  # Get 5th value from last

1
6
4
2


In [207]:
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [208]:
print("(0,0):",array2d[0, 0])   # Get first row first col
print("(0,1):",array2d[0, 1])   # Get first row second col
print("(0,2):",array2d[0, 2])   # Get first row third col
print("(1,1):",array2d[1, 1])   # Get second row second col
print("(2,1):",array2d[2, 1])   # Get third row second col

(0,0): 1
(0,1): 2
(0,2): 3
(1,1): 5
(2,1): 8


### Single Dimensional Slicing

Slicing allows to extract portions of an array or select a subset of an existing array to generate new arrays. For slicing a sequence of numbers separated by colons (`:`) within square brackets.

In [209]:
array1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print('array1d:',array1d)

print("[4:]:",array1d[4:])  # From index 4 to last index
 
print("[:4]:",array1d[:4])  # From index 0 to 4 index
 
print("[4:7]:",array1d[4:7])  # From index 4(included) up to index 7(excluded)

print("[1:7:2]:",array1d[1:7:2])  # From index 1(included) up to index 7(excluded) with step 2

print("[:-1]:",array1d[:-1])  # Excluded last element
 
print("[:-2]:",array1d[:-2])  # Up to second last index(negative index)
 
print("[::-1]:",array1d[::-1])  # From last to first in reverse order(negative step)
 
print("[::-2]:",array1d[::-2])  # All odd numbers in reversed order
 
print("[-2::-2]:",array1d[-2::-2])  # All even numbers in reversed order
 
print("[::]:",array1d[::])  # All elements

array1d: [0 1 2 3 4 5 6 7 8 9]
[4:]: [4 5 6 7 8 9]
[:4]: [0 1 2 3]
[4:7]: [4 5 6]
[1:7:2]: [1 3 5]
[:-1]: [0 1 2 3 4 5 6 7 8]
[:-2]: [0 1 2 3 4 5 6 7]
[::-1]: [9 8 7 6 5 4 3 2 1 0]
[::-2]: [9 7 5 3 1]
[-2::-2]: [8 6 4 2 0]
[::]: [0 1 2 3 4 5 6 7 8 9]


### Multidimensional Slicing

For a two-dimensional array, the same slicing syntax applies, but it is separately defined for the rows and columns.

In [210]:
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [211]:
print(array2d[:, 0:2])  # 1st and 2nd col

[[1 2]
 [4 5]
 [7 8]]


In [212]:
print(array2d[1:3, 0:3])  # 2nd and 3rd row

[[4 5 6]
 [7 8 9]]


In [213]:
print(array2d[-1::-1, -1::-1])  # Reverse an array

[[9 8 7]
 [6 5 4]
 [3 2 1]]


The `transpose` function permutes the dimensions of an array.

In [214]:
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [215]:
# Permute the dimensions of an array.
arrayT = np.transpose(array2d)
print(arrayT)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [216]:
print(array2d.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Joining and Stacking

*Numpy* provide a number of functions to perform: *vertical stacking* (row wise) using `vstack` and *horizontal stacking* (column wise) using `hstack`. 

In [217]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
print(array1)
print('-'*10)
print(array2)

[[1 2 3]
 [4 5 6]]
----------
[[ 7  8  9]
 [10 11 12]]


In [218]:
# Stack arrays in sequence horizontally (column wise).
arrayH = np.hstack((array1, array2))
print(arrayH)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [219]:
# Stack arrays in sequence vertically (row wise).
arrayV = np.vstack((array1, array2))
print(arrayV)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


The `concatenate` function creates a new array by appending arrays after each other, along a given axis. 

In [220]:
# Appending arrays after each other, along a given axis (default axis 0).
arrayC = np.concatenate((array1, array2, array1))
print(arrayC)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [ 1  2  3]
 [ 4  5  6]]


In [221]:
# Appending arrays after each other, along a given axis.
arrayC = np.concatenate((array1, array2, array1), axis=1)
print(arrayC)

[[ 1  2  3  7  8  9  1  2  3]
 [ 4  5  6 10 11 12  4  5  6]]


The `append` function appends an element to an array and creates a new copy of the array.

In [222]:
# Append values to the end of an array.
arrayA = np.append(array1, array2, axis=0)
print(arrayA)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [223]:
arrayA = np.append(array1, array2, axis=1)
print(arrayA)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## Arithmetic Operations

The arithmetic operations with Numpy arrays perform element-wise operations, this means the operators are applied only between corresponding elements.

In [224]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
print(array1)
print('-'*10)
print(array2)

[[1 2 3]
 [4 5 6]]
----------
[[ 7  8  9]
 [10 11 12]]


In [225]:
print(array1 + array2)

[[ 8 10 12]
 [14 16 18]]


In [226]:
print(array1 - array2)

[[-6 -6 -6]
 [-6 -6 -6]]


In [227]:
print(array1 * array2)

[[ 7 16 27]
 [40 55 72]]


In [228]:
print(array2 / array1)

[[7.  4.  3. ]
 [2.5 2.2 2. ]]


In [229]:
print(array1 ** array2)

[[         1        256      19683]
 [   1048576   48828125 2176782336]]


## Scalar Arithmetic Operations

During scalar operations, the scalar value is applied to each element in the array.

In [230]:
array1 = np.array([[10, 20, 30], [40, 50, 60]])
print("array\n",array1)

array
 [[10 20 30]
 [40 50 60]]


In [231]:
print(array1 + 2)

[[12 22 32]
 [42 52 62]]


In [232]:
print(array1 - 5)

[[ 5 15 25]
 [35 45 55]]


In [233]:
print(array1 * 2)

[[ 20  40  60]
 [ 80 100 120]]


In [234]:
print(array1 / 5)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]


In [235]:
print(array1 ** 2)

[[ 100  400  900]
 [1600 2500 3600]]


## Elementary Mathematical Functions

These mathematical functions takes a single array of any dimension as input and returns a new array of the same shape.

- `np.cos`, `np.sin`, `np.tan` : Trigonometric functions.
- `np.arccos`, `np.arcsin`, `np.arctan` : Inverse trigonometric functions.
- `np.cosh`, `np.sinh`, `np.tanh` : Hyperbolic trigonometric functions.
- `np.arccosh`, `np.arcsinh`, `np.arctanh` : Inverse hyperbolic trigonometric functions.
- `np.sqrt` : Square root.
- `np.exp` : Exponential.
- `np.log`, `np.log2`, `np.log10` : Logarithms of base e, 2, and 10, respectively.

In [236]:
array1 = np.array([[10, 20, 30], [40, 50, 60]])

In [237]:
print(np.sin(array1))

[[-0.54402111  0.91294525 -0.98803162]
 [ 0.74511316 -0.26237485 -0.30481062]]


In [238]:
print(np.cos(array1))

[[-0.83907153  0.40808206  0.15425145]
 [-0.66693806  0.96496603 -0.95241298]]


In [239]:
print(np.tan(array1))

[[ 0.64836083  2.23716094 -6.4053312 ]
 [-1.11721493 -0.27190061  0.32004039]]


In [240]:
print(np.sqrt(array1))

[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]


In [241]:
print(np.exp(array1))

[[2.20264658e+04 4.85165195e+08 1.06864746e+13]
 [2.35385267e+17 5.18470553e+21 1.14200739e+26]]


In [242]:
print(np.log10(array1))

[[1.         1.30103    1.47712125]
 [1.60205999 1.69897    1.77815125]]


## Element-wise Mathematical Operations

- `np.add`, `np.subtract`, `np.multiply`, `np.divide` : Addition, subtraction, multiplication, and division of arguments (numpy arrays) element-wise.
- `np.power` : First array elements raised to powers from second array, element-wise.
- `np.remainder` : Return element-wise remainder of division.
- `np.reciprocal` : Return the reciprocal of the argument, element-wise.
- `np.sign`, `np.abs` : Return sign and the absolute value.
- `np.floor`, `np.ceil` : Return the floor, ceiling of the input, element-wise.
- `np.round` : Round a number to a given precision in decimal digits (default 0 digits).

In [243]:
array1 = np.array([[10, 20, 30], [40, 50, 60]])
array2 = np.array([[2, 3, 4], [4, 6, 8]])
array3 = np.array([[-2, 3.5, -4], [4.05, -6, 8]])

In [244]:
print(np.add(array1, array2))

[[12 23 34]
 [44 56 68]]


In [245]:
print(np.power(array1, array2))

[[            100            8000          810000]
 [        2560000     15625000000 167961600000000]]


In [246]:
print(np.remainder((array2), 5))

[[2 3 4]
 [4 1 3]]


In [247]:
print(np.reciprocal(array3))

[[-0.5         0.28571429 -0.25      ]
 [ 0.24691358 -0.16666667  0.125     ]]


In [248]:
print(np.sign(array3))

[[-1.  1. -1.]
 [ 1. -1.  1.]]


In [249]:
print(np.ceil(array3))

[[-2.  4. -4.]
 [ 5. -6.  8.]]


In [250]:
print(np.round(array3))

[[-2.  4. -4.]
 [ 4. -6.  8.]]


## Aggregate and Statistical Functions

- `np.mean` : Compute the arithmetic mean along the specified axis.
- `np.std` : Compute the standard deviation along the specified axis.
- `np.var` : Compute the variance along the specified axis.
- `np.sum` : Sum of array elements over a given axis.
- `np.prod` : Return the product of array elements over a given axis.
- `np.cumsum` : Return the cumulative sum of the elements along a given axis.
- `np.cumprod` : Return the cumulative product of elements along a given axis.
- `np.min`, `np.max` : Return the minimum / maximum of an array or minimum along an axis.
- `np.argmin`, `np.argmax` : Returns the indices of the minimum / maximum values along an axis
- `np.all` : Test whether all array elements along a given axis evaluate to True.
- `np.any` : Test whether any array element along a given axis evaluates to True.

In [251]:
array1 = np.array([[10, 20, 30], [40, 50, 60]])

In [252]:
print("Mean: ", np.mean(array1))
 
print("Std: ", np.std(array1))
 
print("Var: ", np.var(array1))
 
print("Sum: ", np.sum(array1))
 
print("Prod: ", np.prod(array1))

Mean:  35.0
Std:  17.07825127659933
Var:  291.6666666666667
Sum:  210
Prod:  720000000


## Logical Operations

The `logical_or`function, computes the truth value of _x1_ **OR** _x2_ element-wise. `logical_and` computes the truth value of _x1_ **AND** _x2_ element-wise. `logical_not` computes the truth value of **NOT** _x_ element-wise.

In [253]:
array = np.array([[10, 20, 30], [14, 24, 36]])

In [254]:
array<22

array([[ True,  True, False],
       [ True, False, False]])

In [255]:
print(np.logical_or(array < 10, array > 15))

[[False  True  True]
 [False  True  True]]


In [256]:
print(np.logical_and(array < 10, array > 15))

[[False False False]
 [False False False]]


In [257]:
print(np.logical_not(array < 20))

[[False  True  True]
 [False  True  True]]


## Matrix Operations

The `transpose` function permutes the dimensions of an array.

In [258]:
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [259]:
# Permute the dimensions of an array.
arrayT = np.transpose(array2d)

print(arrayT)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [260]:
# as an array method 
print(array2d.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Reductions

Sum along an axis can be done by specifying the interested axis

In [261]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [262]:
# Sum each column
array2d.sum(axis=0)

array([12, 15, 18])

In [263]:
# Sum each row
array2d.sum(axis=1)

array([ 6, 15, 24])

The same axis selection is applicable to `max`, `min`, `argmax`, `argmin`

In [264]:
array2d[2][1] = 0
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 9]])

In [265]:
array2d.max(axis=1) # Max value along each row

array([3, 6, 9])

In [266]:
array2d.argmin(axis=0) # Position on each column of the minimum value

array([0, 2, 0])

We can sort the elements on each row or column using the `axis` parameter

In [267]:
array2d.sort(axis=0) # Sort each column
array2d

array([[1, 0, 3],
       [4, 2, 6],
       [7, 5, 9]])

### Linear Algebra Operations

Computing the vector **dot product** for the two vectors can be calculated by multiplying the corresponding elements of the two vectors and then adding the results from the products.

In [ ]:
x = np.array([2,4])
y = np.array([1,3])

In [ ]:
z = x * y
print(z)
res = z.sum()
print(res)

[ 2 12]
14


As we mentioned before, the `*` operates at element-wise level. To multiply matrices we can use the `dot` method and the `@` operator for matrix multiplication 

In [ ]:
x.dot(y)

14

In [ ]:
x

array([2, 4])

In [ ]:
y

array([1, 3])

In [ ]:
x @ y

14

In [ ]:
mat1 = np.array([[1,2,3],[4,5,6]])
mat2 = np.array([[1],[10],[100]])
print("--- mat1 ---\n",mat1)
print("--- mat2 ---\n",mat2)

--- mat1 ---
 [[1 2 3]
 [4 5 6]]
--- mat2 ---
 [[  1]
 [ 10]
 [100]]


In [ ]:
mat1 @ mat2

array([[321],
       [654]])

In [ ]:
mat1.dot(mat2)

array([[321],
       [654]])

# Pandas - short introduction (only)

In [ ]:
# pip install pandas

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 10.8 MB 1.8 MB/s eta 0:00:01    |█                               | 317 kB 1.8 MB/s eta 0:00:06     |███                             | 1.0 MB 1.8 MB/s eta 0:00:06
     |████████████████████████████████| 509 kB 72.0 MB/s eta 0:00:01     |██████████████████▋             | 296 kB 72.0 MB/s eta 0:00:01
     |████████████████████████████████| 348 kB 64.4 MB/s eta 0:00:01
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


Pandas is a open source Python library for data analysis. It provides high-performance and easy-to-use data structures and data analysis tools built with the Python programming language. Pandas provides a set of tools to perform powerful data manipulations, and discover information in a simple and fast way.

Pandas offers functions to index, retrieve, tidy, reshape, combine, slice, and perform various analyses on both single and multidimensional data, including heterogeneous typed data that is automatically aligned along index labels.

In [271]:
import pandas as pd

## Object creation

There are two types of data structures in *pandas*: `Series` and `DataFrame`.

### Series
`Series` is a one dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, etc.) and for every value it holds a unique index 

Creating a `Series` by passing a list of values, letting pandas create a default integer index:

In [272]:
serie1 = pd.Series([1,2,3,np.nan,5]) # default integer index
print(serie1)
print(serie1.index)

0    1.0
1    2.0
2    3.0
3    NaN
4    5.0
dtype: float64
RangeIndex(start=0, stop=5, step=1)


In [273]:
serie2 = pd.Series(['one','two','three','four','five'])
print(serie2)

0      one
1      two
2    three
3     four
4     five
dtype: object


In [274]:
data = np.array([1,2,3,4,5,6]) # Based on numpy 
serie4 = pd.Series(data)
print(serie4)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


In [275]:
data

array([1, 2, 3, 4, 5, 6])

In [276]:
serie3 = pd.Series([1,'two',3.0,['four','five']]) # Mix of data types
print(serie3)

0               1
1             two
2             3.0
3    [four, five]
dtype: object


Specification of index and data using a Python dictionary 

In [277]:
serie4 = pd.Series({'one':1.0, 'two':2.0, 'three':3, 'four':4}) 
print(serie4)
print(serie4.index)

one      1.0
two      2.0
three    3.0
four     4.0
dtype: float64
Index(['one', 'two', 'three', 'four'], dtype='object')


Creating a `Series` with a specific index names and the same value for all data

In [278]:
pd.Series(13, index=['a','b','c','d'])

a    13
b    13
c    13
d    13
dtype: int64

### DataFrame

`DataFrame` is a 2-dimensional labeled data structure with columns of potentially different types (like a spreadsheet or SQL table, or a dict of Series objects). `DataFrame` accepts many different kinds of input:

- Dict of 1D ndarrays, lists, dicts, or Series
- 2-D numpy.ndarray
- Structured or record ndarray
- A Series
- Another DataFrame

Along with the data, you can optionally pass index (row labels) and columns (column labels) arguments. 

In [279]:
data = {'odd':[1,3,5,7],'even':[0,2,4,6],'name':['one','two','three','four'],'serie':serie3}
df1 = pd.DataFrame(data)
df1

,odd,even,name,serie
0,1,0,one,1
1,3,2,two,two
2,5,4,three,3.0
3,7,6,four,"[four, five]"


In [280]:
pd.DataFrame(np.random.rand(12).reshape((3,4)))

,0,1,2,3
0,0.347340,0.395586,0.027328,0.179966
1,0.430335,0.940664,0.913405,0.285383
2,0.587232,0.376616,0.087503,0.091689


In [281]:
df2 = pd.DataFrame(np.random.rand(24).reshape((6,4)), columns=['one','two','three','four'])
df2

,one,two,three,four
0,0.401455,0.851944,0.022732,0.328342
1,0.958375,0.841039,0.420345,0.149373
2,0.670541,0.630735,0.860808,0.186606
3,0.675257,0.267319,0.199880,0.434456
4,0.568737,0.887164,0.028380,0.476954
5,0.149518,0.661447,0.110085,0.958791


## Viewing data

The `head` method returns the first rows on a DataFrame. If a parameter is given, `head` returns the first asked rows.

In [282]:
df2.head(4)

,one,two,three,four
0,0.401455,0.851944,0.022732,0.328342
1,0.958375,0.841039,0.420345,0.149373
2,0.670541,0.630735,0.860808,0.186606
3,0.675257,0.267319,0.199880,0.434456


The `tail` method returns the last rows on a DataFrame. If a parameter is given, `tail` returns the last asked rows.

In [283]:
df2.tail(3)

,one,two,three,four
3,0.675257,0.267319,0.199880,0.434456
4,0.568737,0.887164,0.028380,0.476954
5,0.149518,0.661447,0.110085,0.958791


The `sample` method returns the specified number of data samples (rows).

In [284]:
df2.sample(3)

,one,two,three,four
0,0.401455,0.851944,0.022732,0.328342
1,0.958375,0.841039,0.420345,0.149373
5,0.149518,0.661447,0.110085,0.958791


The `index` attribute returns the indexes, and the `columns` attribute returns the DataFrame column names

In [285]:
df1.index

RangeIndex(start=0, stop=4, step=1)

In [286]:
df1.columns

Index(['odd', 'even', 'name', 'serie'], dtype='object')

It is possible convert a DataFrame into a *numpy* matrix using the attribute `value`, and apply all the operations supported by numpy

In [287]:
mat = df2.values
print(mat)
print(type(mat))
print(mat.shape)

[[0.40145536 0.85194436 0.02273195 0.3283425 ]
 [0.95837486 0.84103881 0.42034524 0.14937349]
 [0.67054065 0.63073487 0.86080793 0.18660622]
 [0.67525672 0.26731862 0.19988046 0.43445554]
 [0.56873735 0.8871642  0.02838043 0.47695419]
 [0.14951794 0.6614475  0.11008539 0.95879072]]
<class 'numpy.ndarray'>
(6, 4)


In [288]:
type(mat[1,2])

numpy.float64

## Reading/writing from/to files

Pandas supports reading and writing data from different formats (CSV, Excel, JSON, SQL, SAS, etc.). All the functions to read data starts with the `read_` prifix and for write the `write_` prefix.

In [289]:
df1 = pd.read_csv("data/Advertising.csv")
df1.head()

,Unnamed: 0,TV,radio,newspaper,sales
0,1,230.1,37.8,69.2,22.1
1,2,44.5,39.3,45.1,10.4
2,3,17.2,45.9,69.3,9.3
3,4,151.5,41.3,58.5,18.5
4,5,180.8,10.8,58.4,12.9


We can use a local file or an URL to specify the data source

In [290]:
# Mosquitoes Trap Locations
df2 = pd.read_csv("https://data.edmonton.ca/api/views/rh82-ntt9/rows.csv?accessType=DOWNLOAD")
df2.head()

,TRAP_LOCATION,LATITUDE,LONGITUDE,LOCATION
0,Outer Community-North,53.619232,-113.712798,POINT (-113.7127984 53.6192317)
1,River Valley-West,53.504068,-113.570126,POINT (-113.5701263 53.5040684)
2,Rural-West,53.562973,-113.787353,POINT (-113.787353 53.5629733)
3,Outer Community-South2,53.262430,-113.537310,POINT (-113.53731 53.26243)
4,Residential-West,53.552077,-113.643691,POINT (-113.643691 53.552077)


## Handling missing data

It is normal have data with missing values for some columns. Usually, we can handle this issue by three options: ignoring the missing data because it is not relevant, use only data (rows) with complete data, or fill the missing values. 

In [291]:
df = pd.read_table("https://data.edmonton.ca/api/views/qhi4-bdpu/rows.csv?accessType=DOWNLOAD", delimiter=',')
df.head()

,Category,Trade Name,Address,Licence Number,Licence Status,Issue Date,Expiry Date,Business Improvement Area,Neighbourhood ID,Neighbourhood,Ward,Latitude,Longitude,Location,Count,Geometry Point
0,Retail Sales (Minor),LEWIS ESTATES PHARMACY,31 - LEWIS ESTATES BOULEVARD NW,484073154-001,Issued,"Aug 22, 2024","Oct 02, 2025",NaN,4710.0,Potter Greens,Nakota Isga,53.513849,-113.677046,"(53.51384905432644, -113.67704557051144)",1,POINT (-113.67704557051144 53.51384905432644)
1,"Personal Service, Health Enhancement Centre (A...",M SQUARE WELLNESS,NaN,497623601-001,Issued,"Feb 27, 2024","Feb 26, 2025",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
2,"Construction, Contracting, and Labour Service",432 YUCK INC,NaN,458299159-002,Issued,"Dec 29, 2022","Dec 28, 2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
3,Retail Sales (Minor),BUY & BEYOND GOLD SHOPPE,NaN,395798785-002,Issued,"Apr 25, 2024","May 18, 2025",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
4,"Construction, Contracting, and Labour Service",BAI MARR ENTERPRISES,NaN,438689983-002,Issued,"Jul 04, 2024","Jul 05, 2025",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN


To determine how our data is in terms of missing data, we can count the values for each column

In [292]:
df.count()

Category                     37708
Trade Name                   37707
Address                      23326
Licence Number               37708
Licence Status               37708
Issue Date                   37707
Expiry Date                  37708
Business Improvement Area     4837
Neighbourhood ID             22781
Neighbourhood                22781
Ward                         22781
Latitude                     22781
Longitude                    22781
Location                     22781
Count                        37708
Geometry Point               22781
dtype: int64

In this case, `Business Improvement Area` column has the least number of valid values. To reduce our data to only use rows with valid data, we can *drop* the rows with missing values

In [293]:
df2 = df.dropna()
df2.count()

Category                     4836
Trade Name                   4836
Address                      4836
Licence Number               4836
Licence Status               4836
Issue Date                   4836
Expiry Date                  4836
Business Improvement Area    4836
Neighbourhood ID             4836
Neighbourhood                4836
Ward                         4836
Latitude                     4836
Longitude                    4836
Location                     4836
Count                        4836
Geometry Point               4836
dtype: int64

In [294]:
df2

,Category,Trade Name,Address,Licence Number,Licence Status,Issue Date,Expiry Date,Business Improvement Area,Neighbourhood ID,Neighbourhood,Ward,Latitude,Longitude,Location,Count,Geometry Point
53,"Restaurant or Food Service, Alcohol Sales (Con...",BAR HENRY,"160, 10220 - 103 AVENUE NW",486870375-001,Issued,"Nov 24, 2023","Nov 23, 2024",Downtown,1090.0,Downtown,O-day'min,53.545358,-113.497010,"(53.545358031048, -113.49700960020199)",1,POINT (-113.49700960020199 53.545358031048)
67,Retail Sales (Minor),THE WHITE GALLERY,12403 - STONY PLAIN ROAD NW,480756073-001,Issued,"Jan 16, 2024","Jan 15, 2025",124 Street and Area,3440.0,Westmount,O-day'min,53.546573,-113.536385,"(53.54657303566164, -113.53638459097274)",1,POINT (-113.53638459097274 53.54657303566164)
128,Retail Sales (Minor),SUNGLASS HUT #4288,"173, 1 - KINGSWAY GARDEN MALL NW",503481892-001,Issued,"May 16, 2024","May 15, 2025",Kingsway,1230.0,Spruce Avenue,O-day'min,53.562305,-113.505555,"(53.56230503106817, -113.50555509259978)",1,POINT (-113.50555509259978 53.56230503106817)
146,"Retail Sales (Major), Second Hand Dealer",MCBAIN CAMERA,10805 - 107 AVENUE NW,340594532-002,Issued,"Jan 17, 2024","Dec 01, 2024",North Edge,1030.0,Central McDougall,O-day'min,53.551235,-113.507121,"(53.55123503190527, -113.50712109596437)",1,POINT (-113.50712109596437 53.55123503190527)
207,Residential Rental Accommodation (Long-Term),DEMELO CONTRACTING INC.,11732 - 124 STREET NW,396884713-002,Issued,"Jul 11, 2024","Jul 10, 2025",The Crossroads,3240.0,Inglewood,Anirniq,53.569433,-113.536448,"(53.56943303432732, -113.53644758328268)",1,POINT (-113.53644758328268 53.56943303432732)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37659,Restaurant or Food Service,SZECHUAN GARDEN RESTAURANT,8907 - 118 AVENUE NW,138864184-001,Issued,"Jun 12, 2024","Jun 18, 2025",Alberta Avenue,1010.0,Alberta Avenue,Métis,53.570099,-113.478659,"(53.57009902740909, -113.478658596014)",1,POINT (-113.478658596014 53.57009902740909)
37671,"Construction, Contracting, and Labour Service",SMART HOME BUILDING SYSTEMS LTD,17704 - 118 AVENUE NW,294833549-002,Issued,"Oct 24, 2023","Nov 19, 2025",Northwest Industrial,4130.0,Edmiston Industrial,Nakota Isga,53.570801,-113.625615,"(53.570801044870024, -113.6256150628693)",1,POINT (-113.6256150628693 53.570801044870024)
37678,Public Market Vendor,O'NEILL ESTHER,12011 - 111 AVENUE NW,307878543-002,Issued,"Feb 22, 2024","Mar 20, 2026",Kingsway,1180.0,Queen Mary Park,O-day'min,53.558066,-113.529864,"(53.55806603421058, -113.5298640885757)",1,POINT (-113.5298640885757 53.55806603421058)
37692,"Restaurant or Food Service, Alcohol Sales (Con...",MALT & MORTAR,10416 - 82 AVENUE NW,223958139-002,Renewal Notice,"Sep 22, 2023","Oct 03, 2024",Old Strathcona,5480.0,Strathcona,papastew,53.518394,-113.498256,"(53.518394032784485, -113.49825610895634)",1,POINT (-113.49825610895634 53.518394032784485)


In case that we only are interested in have rows with values on a specific column

In [295]:
df2 = df[df.Address.notna()]
df2.count()

Category                     23326
Trade Name                   23325
Address                      23326
Licence Number               23326
Licence Status               23326
Issue Date                   23325
Expiry Date                  23326
Business Improvement Area     4837
Neighbourhood ID             22781
Neighbourhood                22781
Ward                         22781
Latitude                     22781
Longitude                    22781
Location                     22781
Count                        23326
Geometry Point               22781
dtype: int64

In [296]:
df.head()

,Category,Trade Name,Address,Licence Number,Licence Status,Issue Date,Expiry Date,Business Improvement Area,Neighbourhood ID,Neighbourhood,Ward,Latitude,Longitude,Location,Count,Geometry Point
0,Retail Sales (Minor),LEWIS ESTATES PHARMACY,31 - LEWIS ESTATES BOULEVARD NW,484073154-001,Issued,"Aug 22, 2024","Oct 02, 2025",NaN,4710.0,Potter Greens,Nakota Isga,53.513849,-113.677046,"(53.51384905432644, -113.67704557051144)",1,POINT (-113.67704557051144 53.51384905432644)
1,"Personal Service, Health Enhancement Centre (A...",M SQUARE WELLNESS,NaN,497623601-001,Issued,"Feb 27, 2024","Feb 26, 2025",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
2,"Construction, Contracting, and Labour Service",432 YUCK INC,NaN,458299159-002,Issued,"Dec 29, 2022","Dec 28, 2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
3,Retail Sales (Minor),BUY & BEYOND GOLD SHOPPE,NaN,395798785-002,Issued,"Apr 25, 2024","May 18, 2025",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
4,"Construction, Contracting, and Labour Service",BAI MARR ENTERPRISES,NaN,438689983-002,Issued,"Jul 04, 2024","Jul 05, 2025",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN


If we want to fill the missing values with some specific value, we can use the method `fillna`

In [297]:
df['Business Improvement Area'].head()

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: Business Improvement Area, dtype: object

In [298]:
df2 = df.fillna({'Business Improvement Area':'Edmonton'})
df2.head()

,Category,Trade Name,Address,Licence Number,Licence Status,Issue Date,Expiry Date,Business Improvement Area,Neighbourhood ID,Neighbourhood,Ward,Latitude,Longitude,Location,Count,Geometry Point
0,Retail Sales (Minor),LEWIS ESTATES PHARMACY,31 - LEWIS ESTATES BOULEVARD NW,484073154-001,Issued,"Aug 22, 2024","Oct 02, 2025",Edmonton,4710.0,Potter Greens,Nakota Isga,53.513849,-113.677046,"(53.51384905432644, -113.67704557051144)",1,POINT (-113.67704557051144 53.51384905432644)
1,"Personal Service, Health Enhancement Centre (A...",M SQUARE WELLNESS,NaN,497623601-001,Issued,"Feb 27, 2024","Feb 26, 2025",Edmonton,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
2,"Construction, Contracting, and Labour Service",432 YUCK INC,NaN,458299159-002,Issued,"Dec 29, 2022","Dec 28, 2024",Edmonton,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
3,Retail Sales (Minor),BUY & BEYOND GOLD SHOPPE,NaN,395798785-002,Issued,"Apr 25, 2024","May 18, 2025",Edmonton,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
4,"Construction, Contracting, and Labour Service",BAI MARR ENTERPRISES,NaN,438689983-002,Issued,"Jul 04, 2024","Jul 05, 2025",Edmonton,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN


In [299]:
df.describe()

,Neighbourhood ID,Latitude,Longitude,Count
count,22781.000000,22781.000000,22781.000000,37708.0
mean,4298.810719,53.527662,-113.510702,1.0
std,1949.422558,0.048734,0.072317,0.0
min,1010.000000,53.343299,-113.712807,1.0
25%,2550.000000,53.493122,-113.568596,1.0
50%,4520.000000,53.539526,-113.496083,1.0
75%,6180.000000,53.561981,-113.467908,1.0
max,8888.000000,53.705153,-113.289551,1.0
